// <auto-generated />
using System;
using API.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Models.FrequencyType", b =>
                {
                    b.Property<int>("FrequencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FrequencyTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyTypeId"));

                    b.Property<string>("FrequencyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FrequencyTypeId")
                        .HasName("PK__Frequenc__829BB4DCA6980AEF");

                    b.ToTable("FrequencyTypes");
                });

            modelBuilder.Entity("API.Data.Models.Habit", b =>
                {
                    b.Property<int>("HabitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HabitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitId"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("FrequencyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FrequencyTypeID");

                    b.Property<string>("HabitName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF__Habits__IsArchiv__4316F928");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("HabitId")
                        .HasName("PK__Habits__C587AF03B94969EF");

                    b.HasIndex("FrequencyTypeId");

                    b.HasIndex(new[] { "UserId" }, "idx_Habits_UserID");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("API.Data.Models.HabitCompletion", b =>
                {
                    b.Property<int>("CompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompletionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletionId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("HabitId")
                        .HasColumnType("int")
                        .HasColumnName("HabitID");

                    b.Property<string>("Notes")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.HasKey("CompletionId")
                        .HasName("PK__HabitCom__77FA70AFF5B2F7EF");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "HabitId" }, "idx_HabitCompletions_HabitID");

                    b.HasIndex(new[] { "HabitId", "CompletionDate" }, "uq_Habit_CompletionDate")
                        .IsUnique()
                        .HasFilter("[CompletionDate] IS NOT NULL");

                    b.ToTable("HabitCompletions");
                });

            modelBuilder.Entity("API.Data.Models.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReminderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderId"));

                    b.Property<int>("HabitId")
                        .HasColumnType("int")
                        .HasColumnName("HabitID");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("ReminderId")
                        .HasName("PK__Reminder__01A830A79BBE095C");

                    b.HasIndex("HabitId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("API.Data.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int>("ImpactScore")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("StatusId")
                        .HasName("PK__Status__C8EE2043A5F1AC3E");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("API.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varbinary(250)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC9237AFDB");

                    b.HasIndex(new[] { "Email" }, "uq_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Data.Models.Habit", b =>
                {
                    b.HasOne("API.Data.Models.FrequencyType", "FrequencyType")
                        .WithMany("Habits")
                        .HasForeignKey("FrequencyTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_frequencyType");

                    b.HasOne("API.Data.Models.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_Habits_User");

                    b.Navigation("FrequencyType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Data.Models.HabitCompletion", b =>
                {
                    b.HasOne("API.Data.Models.Habit", "Habit")
                        .WithMany("HabitCompletions")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_HabitCompletions_Habit");

                    b.HasOne("API.Data.Models.Status", "Status")
                        .WithMany("HabitCompletions")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("fk_status");

                    b.Navigation("Habit");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("API.Data.Models.Reminder", b =>
                {
                    b.HasOne("API.Data.Models.Habit", "Habit")
                        .WithMany("Reminders")
                        .HasForeignKey("HabitId")
                        .IsRequired()
                        .HasConstraintName("fk_Reminders_Habit");

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("API.Data.Models.FrequencyType", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("API.Data.Models.Habit", b =>
                {
                    b.Navigation("HabitCompletions");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("API.Data.Models.Status", b =>
                {
                    b.Navigation("HabitCompletions");
                });

            modelBuilder.Entity("API.Data.Models.User", b =>
                {
                    b.Navigation("Habits");
                });
#pragma warning restore 612, 618
        }
    }
}
